HDF5/ASDF Comparison
asdf-format/asdf_documents pull request #1
Opened 2022-10-10 20:05 UTC by perrygreenfield

The edited version used for PLATO. If someone know how to deal with the odd breaks in the displayed code, let me know. I used rst2pdf to generate the PDFs.

2022-10-10 20:10 UTC, WilliamJamieson commented
Can you copy in the `.pre-commit-config.yaml` from `asdf`? That way pre-commit is happy. It might fix-up some things..

2022-10-10 20:11 UTC, WilliamJamieson commented
> I used rst2pdf to generate the PDFs.

Also, once this is in I could go ahead and setup RTD to generate the docs for this if you want.

2022-10-11 09:26 UTC, nden commented on general/hdf5_asdf_comparison.rst
> +Based on a number of questions and comments about why we aren't using HDF5, that the first ASDF paper apparently hasn't addressed suitably well, this document is an attempt to explain in more detail
Should we have a reference or a link to the ASDF paper?

2022-10-11 09:26 UTC, nden commented on general/hdf5_asdf_comparison.rst
> +6. HDF5 Abstract Data Model not flexible enough.
```suggestion
6. HDF5 Abstract Data Model not flexible enough

```

2022-10-11 09:26 UTC, nden commented on general/hdf5_asdf_comparison.rst
> +A small segment of the contents of the HDF5 file is displayed in Appendix E to contrast the difficulty of directly interpreting the contents as compared to ASDF. In the ASCII rendition one can see wh
```suggestion
A small segment of the contents of the HDF5 file is displayed in `Appendix E`_ to contrast the difficulty of directly interpreting the contents as compared to ASDF. In the ASCII rendition one can see where some keys are located, but not much beyond that.

```

2022-10-11 09:26 UTC, nden commented on general/hdf5_asdf_comparison.rst
> +A small segment of the contents of the HDF5 file is displayed in Appendix E to contrast the difficulty of directly interpreting the contents as compared to ASDF. In the ASCII rendition one can see wh
added a link

2022-10-11 11:26 UTC, perrygreenfield commented on general/hdf5_asdf_comparison.rst
> +Based on a number of questions and comments about why we aren't using HDF5, that the first ASDF paper apparently hasn't addressed suitably well, this document is an attempt to explain in more detail
I added one.

2022-10-11 11:27 UTC, perrygreenfield commented on general/hdf5_asdf_comparison.rst
> +A small segment of the contents of the HDF5 file is displayed in Appendix E to contrast the difficulty of directly interpreting the contents as compared to ASDF. In the ASCII rendition one can see wh
fixed reference to Appendix E.

2022-10-11 11:29 UTC, perrygreenfield commented
@WilliamJamieson I did add the pre-commit file. Sure, if you can set up RTD for this that would be great.

2022-10-12 17:58 UTC, WilliamJamieson commented
> @WilliamJamieson I did add the pre-commit file. Sure, if you can set up RTD for this that would be great.

PR #2 adds the ability to support docs building. I will setup RTD for this repo shortly.

2022-10-13 12:30 UTC, nden approved these changes

2022-10-13 14:01 UTC, WilliamJamieson requested changes
Can `hdf5_asdf_comparison.rst` be moved into the `docs` directory?

After that can it be added to a `.. toctree::` inside the `index.rst` file?

2022-10-13 14:02 UTC, merged